spring:
  application:
    name: gateway-service # Name in Eureka Dashboard and for config-server
  
  # This setting can't be pushed to the config server, as it falls into an infinite loop searching for the config in itself
  config:
    import: configserver:http://config-server:8888 

  cloud:
    gateway:
      routes:
          # Patterns for routes are all the same
          # If a request is sent to /survey/abc, gateway will forward the request to the survey-service, but only tha abc part
        - id: survey-service # Name of route
          uri: lb://survey-service # Redirection to the actual microservice
          predicates:
            - Path=/survey/** # The path that activates redirection
          filters:
            - RewritePath=/survey/(?<path>.*), /$\{path} # TODO: ????
        - id: campaign-service
          uri: lb://campaign-service
          predicates:
            - Path=/campaign/**
          filters:
            - RewritePath=/campaign/(?<path>.*), /$\{path}
server:
  port: 8889

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
  instance:
    preferIpAddress: true

# Exposing all Actuator endpoints
management.endpoints.web.exposure.include: "*"

# FIXME: ?
# Displayed in /actuator/info
# info:
#   app:
#     name: @project.name@
#     groupId: @project.groupId@
#     artifactId: @project.artifactId@
#     version: @project.version@
#     test: hi!