spring:
  application:
    name: campaign-service # NAME IN EUREKA DASHBOARD
server:
  port: 0 # RANDOM PORT
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true