spring:
  application:
    name: survey-service # Name in Eureka Dashboard
server:
  port: 0 # Random port
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true