version: '3.9'

services:
  eureka-server:
    build: ./eureka-server/
    ports:
      - 8761:8761
  # survey-service:
  #   build: ./survey/survey-service/
  # campaign-service:
  #   build: ./campaign/campaign-service/
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=thedockeruser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=thedockerdb
