spring:
  application:
    name: campaign-service # Name in Eureka Dashboard
  sql:
    init:
      mode: always # Enables data.sql
  jpa:
    defer-datasource-initialization: true # Enables data.sql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://db:5432/thedockerdb 	# jdbc:postgresql://db:5432/thedockerdb ? umesto localhost naziv servisa?
    username: thedockeruser
    password: password
server:
  port: 0 # Random port
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
  instance:
    preferIpAddress: true